//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_AppxServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WEB_AppxServicio()
        {
            this.WEB_AuditoriaAppxServ = new HashSet<WEB_AuditoriaAppxServ>();
        }
    
        public int idsrvapp { get; set; }
        public int idservicio { get; set; }
        public int idapp { get; set; }
        public bool estado { get; set; }
    
        public virtual WEB_Aplicacion WEB_Aplicacion { get; set; }
        public virtual WEB_Servicio WEB_Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEB_AuditoriaAppxServ> WEB_AuditoriaAppxServ { get; set; }
    }
}
