//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_AuditoriaSolicitud
    {
        public int id_auditoria_solicitud { get; set; }
        public int id_solicitud { get; set; }
        public string revisado_por { get; set; }
        public System.DateTime fecha_realizado { get; set; }
        public string estado { get; set; }
    
        public virtual WEB_Solicitud WEB_Solicitud { get; set; }
    }
}
