//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Subordinado
    {
        public int id_subordinado { get; set; }
        public string nombre { get; set; }
        public string mail { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> servicio_id { get; set; }
        public string apellido { get; set; }
        public Nullable<int> dni { get; set; }
        public string nombre_referente { get; set; }
    
        public virtual WEB_Servicio WEB_Servicio { get; set; }
    }
}
