//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Equipo
    {
        public int id_equipo { get; set; }
        public Nullable<int> subordinado_id { get; set; }
        public string mac { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    
        public virtual WEB_Subordinado WEB_Subordinado { get; set; }
        public virtual WEB_TipoEquipo WEB_TipoEquipo { get; set; }
    }
}
